### ISSUE TITLE
Add component : Checkbox & radio

### ISSUE THREAD

**Issue by GuillaumeAmat** [osm-ui/react#12]

**Comment by bleucitron** [comment]
Do you have any particular specs for this one ?

**Comment by GuillaumeAmat** [comment]
Absolutely not ;) 

Just that I would like to have a good style, as in MapContrib v1. It is pretty and consistent with the others components.

**Comment by bleucitron** [comment]
Checkbox was handled by #26.

**Comment by GuillaumeAmat** [comment]
🤟

**Comment by bleucitron** [comment]
Actually, I'll reopen it, since Radio is pending.

**Comment by GuillaumeAmat** [comment]
I need to sleep... ^^'
