### ISSUE TITLE
Fix test warnings

### ISSUE THREAD

**Issue by bleucitron** [osm-ui/react#15]
Currently, tests display these warnings:

```
Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. http://fb.me/react-polyfills
```

They should be removed.

**Comment by GuillaumeAmat** [comment]
I do not see that anymore since that commit: 0afa6f0318d897e9f48a3a4f6c64a3949d33534e

Do you?

**Comment by GuillaumeAmat** [comment]
I close the issue for now but I will reopen it if you still have the warnings.
