### ISSUE TITLE
Icons don't display anymore

### ISSUE THREAD

**Issue by bleucitron** [osm-ui/react#17]
The FontAwesome icons (in the Toolbar section for instance) don't display anymore.

https://osm-ui.github.io/react/?selectedKind=Toolbar&selectedStory=Default%20state&full=0&down=1&left=1&panelRight=1&downPanel=storybooks%2Fstorybook-addon-knobs

**Comment by GuillaumeAmat** [comment]
Yup, I have the same problem on my machine...

**Comment by GuillaumeAmat** [comment]
Ok it's fixed, my bad 😭
