### ISSUE TITLE
Title, Header, Footer: common or separated ?

### ISSUE THREAD

**Issue by bleucitron** [osm-ui/react#19]
Currently `Sidebar` and `Modal` components share the `Sidebar.Title` component.

This is not right.

Two options:
- make a common component in its dedicated folder to be used by both `Sidebar` and `Modal` (and others)
- make each component its own `Title`

This could be discussed for `Header` and `Footer` (that are currently not used by the way).

**Comment by bleucitron** [comment]
My personal opinion is that it should be a common component, for `Title`, `Header` and `Footer`.
They are only "parent" or "style" components.
The only possible differences I can think of are only about styling, which can be addressed with the `className` prop.

**Comment by GuillaumeAmat** [comment]
Yep you're right, I think we can go for it and see what appends next. Warning though, the sidebar's title already has two "display mode": integrated in the header or detached in the content.

Also, keep in mind that the Title, Header and Footer new components, as generics components, should be used without parent at all.
