### ISSUE TITLE
Add component : OSM Feature

### ISSUE THREAD

**Issue by PanierAvide** [osm-ui/react#2]
One must have would be to have a complete component for displaying an OSM feature (node, way, relation). This one might be split in several sub-components (to be discussed).

## Mode
It can be shown in two modes:
* Simple: for end users, not OSM experts, which want to know what a feature is simply (a bakery which is named X, located at this address, and represented by this picture)
* Advanced: for OSM contributors, wanting to have every possible detail about the object (tags, children elements, related changesets...)

## Sub components
A first draft of sub components to consider:
* Human readable name of the feature
* Picture(s) slideshow
* Tags list
* Address
* History of changes
* List of children elements

**Comment by GuillaumeAmat** [comment]
I like that very much :)
