### ISSUE TITLE
Add component : Tile layer selector

### ISSUE THREAD

**Issue by PanierAvide** [osm-ui/react#3]
A component to select which tile layer must be rendered on an application. It might look like the tile selector of main OSM website (or the totally look-alike one of dev.openlevelup.net).

**Comment by GuillaumeAmat** [comment]
@PanierAvide Did you saw the MapContrib's tile layer selector in its last version?

**Comment by PanierAvide** [comment]
Just looked at it. I have a preference for the OSM one as there is no radio button, the selected item is shown by having a green border.

**Comment by GuillaumeAmat** [comment]
How, that's just the style! ;)
I talked about the functional part of it. The « show more » button is a must have IMHO.

**Comment by PanierAvide** [comment]
Is it on mapcontrib.xyz ? I don't see the "Show more" button...

**Comment by GuillaumeAmat** [comment]
You must have seen a theme with all tiles activated ;)
Try on that one: https://www.mapcontrib.xyz/t/18fa92-Les_equipements_lies_aux_dechets#select/tile

**Comment by PanierAvide** [comment]
Oh nice, as you said it is a must have :-)
