### ISSUE TITLE
Get rid of jQuery

### ISSUE THREAD

**Issue by bleucitron** [osm-ui/react#55]
I just tried to add tests for components in [MCNext](https://github.com/mapcontrib/mapcontrib.next), using this config file `jest.setup.js`:

```
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
```

But i get an error stating that `jQuery is not defined`, which points at 
```import { Map as OsmUIMap } from 'osm-ui-react';```

I noticed that in OSM-UI, we have this `jest.setup.js`:
```
import 'raf/polyfill';
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import jQuery from 'jquery';

global.$ = global.jQuery = jQuery;

configure({ adapter: new Adapter() });
```

Could we just get rid of jQuery for once ?

**Comment by GuillaumeAmat** [comment]
I'd loooooove to! Currently jQuery is here because it is a dependency of Bootstrap...

Our two leads are to remove Bootstrap from the project or replace it with Reactstrap. A Bootstrap 4 React library without jQuery.

**Comment by bleucitron** [comment]
Is Bootstrap really used ?
I'm not sure we need it or any substitute.

**Comment by GuillaumeAmat** [comment]
For the css reset and normalize yes, but it can be replaced by another thing.
