### ISSUE TITLE
Basic Icon Picker

### ISSUE THREAD

**Issue by bleucitron** [osm-ui/react#56]
I haven't found a correct Icon picker for React/FontAwesome yet...
So we might have to create our own.

The first step would be to have a basic Icon Picker with a selection of, say, 10 icons.

**Comment by bleucitron** [comment]
I was thinking of installing these libs to get all the icons so that we can display them in the picker:
```
@fortawesome/fontawesome
@fortawesome/fontawesome-free-regular
```
Is this a potential issue for you (in terms of how MC has been using FA for now, or in terms of the additional code weight) ?

(from https://fontawesome.com/how-to-use/use-with-node-js)

**Comment by bleucitron** [comment]
We might need to address #21 before this one.

**Comment by bleucitron** [comment]
@GuillaumeAmat to avoid having to bundle all icons, I wanted to do something like this:
- reference all FA `regular` icons
- add the FA CDN as script/src in `index.html`
- display all icons, or icons 5 by 5 (the loading is done when necessary)

But after reading [this](https://github.com/FortAwesome/react-fontawesome/issues/34), i'm not sure this is possible...
It seems the current [React FontAwesome](https://github.com/FortAwesome/react-fontawesome) strategy is to load manually the icons you need, which is not ideal for our use case.

**Comment by bleucitron** [comment]
The "best" alternative to having all icons available in the picker is then to preselect the icons we believe will be most used, and allow the user to reference the icon if not available (as it is done currently in v1)

**Comment by GuillaumeAmat** [comment]
Hi @iOiurson 👋 Here are my thoughts on those two topics:

Every time I thought that a minimal set of this or that would do the job in the past was a great failure... Icons, locales, colors, etc. Every time 😅 So I'd suggest/prefer to have all the icons from the library, and even more possibility if it is possible. External pictures (like in v1), emoji, etc. It could be done in an iterative way though!

That said, I think the best solution about FontAwesome is to stick to the good ol' webfont/css way: https://fontawesome.com/how-to-use/web-fonts-with-css

That way we just have to load a CSS file and a font file, they can be deferred, cached, etc. It is a good compromise and it works well. What do you think about that?

**Comment by bleucitron** [comment]
Yes i was thinking about something like that too.

But i had problems:
- where is located the `index.html` file in Storybook/Create-React-Apps ?
- how do we get a list of all available icons ?

**Comment by bleucitron** [comment]
For the second point: https://github.com/FortAwesome/Font-Awesome/issues/13356

**Comment by GuillaumeAmat** [comment]
> where is located the index.html file in Storybook/Create-React-Apps ?

For CRA it's in the public folder and for Storybook you just have to import the css in the config/stories.
