### ISSUE TITLE
Is React-test-renderer useful ?

### ISSUE THREAD

**Issue by bleucitron** [osm-ui/react#61]
My guess is that with Jest and Enzyme, we cover most of our needs.

**Comment by GuillaumeAmat** [comment]
Yep, totally 👍

And like I said [here](https://github.com/osm-ui/react/pull/57#issuecomment-414442276), we should stick to `shallow` most of the time to unit/snapshot test the components. `mount` & co should only be used to integration and behavior tests.

**Comment by GuillaumeAmat** [comment]
All the CI are failing these days... really anoying, the tests are too long apparently
