### ISSUE TITLE
Add component : OSM element merge/diff

### ISSUE THREAD

**Issue by GuillaumeAmat** [osm-ui/react#8]
Between two versions of its attributes

**Comment by bleucitron** [comment]
@GuillaumeAmat is this the Osmose component ?

**Comment by GuillaumeAmat** [comment]
@iOiurson Yep, it is part of the Osmose integration in MapContrib.

**Comment by bleucitron** [comment]
To what extent this element should allow tag edition ?

I see there is #7 related, and I was wondering if in the context of [MapContrib projet](https://github.com/mapcontrib/mapcontrib.next) development, we will allow the user to edit the tags, or simply accept/reject fixes proposals provided by Osmose.

**Comment by GuillaumeAmat** [comment]
It is still an open discussion, but it could be a composant which display the differences between 2 version of an OSM element (or 2 different elements) and propose to select the tags we want to keep in order to create a new version fo the element.

After that, we could pass the result to the #7 component which is basically a form with special inputs to ease the contribution to OSM tags/elements.
